#!/bin/sh

#
# ENV variables passed to container. If they are not provided, default values are used.
#
NEOS_APP_DO_INIT=${NEOS_APP_DO_INIT:=true}
NEOS_APP_DO_INIT_TESTS=${NEOS_APP_DO_INIT_TESTS:=false}
NEOS_APP_NAME=${NEOS_APP_NAME:="neos"}
NEOS_APP_DB_NAME=${NEOS_APP_DB_NAME:="typo3_neos"}
NEOS_APP_USER_NAME=${NEOS_APP_USER_NAME:="admin"}
NEOS_APP_USER_PASS=${NEOS_APP_USER_PASS:="password"}
NEOS_APP_USER_FNAME=${NEOS_APP_USER_FNAME:="Admin"}
NEOS_APP_USER_LNAME=${NEOS_APP_USER_LNAME:="User"}
NEOS_APP_VHOST_NAMES=${NEOS_APP_VHOST_NAMES:="${NEOS_APP_NAME} dev.${NEOS_APP_NAME} behat.dev.${NEOS_APP_NAME}"}
NEOS_APP_SITE_PACKAGE=${NEOS_APP_SITE_PACKAGE:=false}
NEOS_APP_FORCE_PULL=${NEOS_APP_FORCE_PULL:=false}
NEOS_APP_FORCE_SITE_REIMPORT=${NEOS_APP_FORCE_SITE_REIMPORT:=false}
NEOS_APP_FORCE_VHOST_CONF_UPDATE=${NEOS_APP_FORCE_VHOST_CONF_UPDATE:=true}
TYPO3_NEOS_COMPOSER_PARAMS=${TYPO3_NEOS_COMPOSER_PARAMS:="--optimize-autoloader"}
NEOS_USER_BUILD_SCRIPT="build.sh" # Script which might be present in $NEOS_ROOT and will be called at the end of the setup process
